// KKFI Admin Data File
// This file contains all scholar and applicant data

const scholars = [
  {
    id: "LM823748",
    firstName: "Carlo",
    middleName: "Navarro",
    lastName: "Flores",
    initials: "CN",
    email: "carlo.flores@email.com",
    phone: "+63 917 234 5678",
    dateOfBirth: "March 15, 2003",
    gender: "Male",
    civilStatus: "Single",
    address: "Block 5, Lot 12, Sunrise Village, Brgy. San Isidro, Quezon City",
    barangay: "San Isidro",
    city: "Quezon City",
    province: "Metro Manila",
    facebook: "facebook.com/carlo.flores",
    messenger: "m.me/carlo.flores",
    school: "Polytechnic University of the Philippines - Main",
    course: "BS Computer Science",
    yearLevel: "3rd Year",
    semester: "1st Semester",
    programLevel: "Undergraduate",
    boardExam: null,
    studentId: "2022-12345",
    scholarSince: "22 Apr 2024",
    status: "compliant",
    gpa: "3.2",
    requiredGpa: "2.5",
    gpaStatus: "Above Required",
    lastGradeSubmission: "Jan 20, 2026",
    eventsAttended: "3 of 3",
    fatherName: "Roberto Navarro Flores",
    fatherOccupation: "OFW (Saudi Arabia)",
    fatherIncome: "₱45,000/month",
    motherName: "Elena Santos Flores",
    motherOccupation: "Housewife",
    motherIncome: "N/A",
    siblings: "2 (1 younger brother, 1 younger sister)",
    familyIncome: "₱45,000/month",
    housingType: "Owned",
    scholarshipType: "Tertiary Scholarship",
    scholarshipAmount: "₱25,000/semester",
    compliance: {
      gpa: { met: true, value: "3.2" },
      grades: { met: true, date: "Jan 20, 2026" },
      events: { met: true, attended: 3, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: true },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: true },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: true },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: true }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "3.2", events: 3, status: "Compliant" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "3.0", events: 4, status: "Compliant" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "2.9", events: 3, status: "Compliant" }
    ]
  },
  {
    id: "LM823747",
    firstName: "Maria",
    middleName: "Cruz",
    lastName: "Dela Rosa",
    initials: "MC",
    email: "maria.cruz@email.com",
    phone: "+63 918 345 6789",
    dateOfBirth: "July 22, 2002",
    gender: "Female",
    civilStatus: "Single",
    address: "Unit 5B, Greenfield Residences, Brgy. Kapitolyo, Pasig City",
    barangay: "Kapitolyo",
    city: "Pasig City",
    province: "Metro Manila",
    facebook: "facebook.com/maria.delarosa",
    messenger: "m.me/maria.delarosa",
    school: "Bulacan State University",
    course: "BS Accountancy",
    yearLevel: "4th Year",
    semester: "2nd Semester",
    programLevel: "Undergraduate",
    boardExam: "CPA Board Exam",
    studentId: "2021-67890",
    scholarSince: "30 Apr 2024",
    status: "compliant",
    gpa: "3.5",
    requiredGpa: "2.5",
    gpaStatus: "Above Required",
    lastGradeSubmission: "Jan 18, 2026",
    eventsAttended: "3 of 3",
    fatherName: "Juan Cruz Dela Rosa",
    fatherOccupation: "Taxi Driver",
    fatherIncome: "₱18,000/month",
    motherName: "Rosa Santos Dela Rosa",
    motherOccupation: "Laundry Worker",
    motherIncome: "₱8,000/month",
    siblings: "3 (2 older brothers, 1 younger sister)",
    familyIncome: "₱26,000/month",
    housingType: "Rented",
    scholarshipType: "KKFI Employee-Child Education Grant",
    scholarshipAmount: "₱30,000/semester",
    compliance: {
      gpa: { met: true, value: "3.5" },
      grades: { met: true, date: "Jan 18, 2026" },
      events: { met: true, attended: 3, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: true },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: true },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: true },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: false }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "3.5", events: 3, status: "Compliant" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "3.4", events: 4, status: "Compliant" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "3.3", events: 3, status: "Compliant" }
    ]
  },
  {
    id: "LM823746",
    firstName: "Mark",
    middleName: "Dizon",
    lastName: "Bautista",
    initials: "MD",
    email: "mark.bautista@email.com",
    phone: "+63 919 456 7890",
    dateOfBirth: "November 8, 2003",
    gender: "Male",
    civilStatus: "Single",
    address: "123 Sampaguita St., Brgy. Bagong Silang, Caloocan City",
    barangay: "Bagong Silang",
    city: "Caloocan City",
    province: "Metro Manila",
    facebook: "facebook.com/mark.bautista",
    messenger: "m.me/mark.bautista",
    school: "Philippine Normal University - Manila",
    course: "Bachelor of Secondary Education",
    yearLevel: "2nd Year",
    semester: "3rd Semester",
    programLevel: "Undergraduate",
    boardExam: "Licensure Exam for Teachers (LET)",
    studentId: "2023-11223",
    scholarSince: "05 May 2024",
    status: "non-compliant",
    gpa: "2.1",
    requiredGpa: "2.5",
    gpaStatus: "Below Required",
    lastGradeSubmission: "Not Submitted",
    eventsAttended: "0 of 3",
    fatherName: "Pedro Dizon Bautista",
    fatherOccupation: "Construction Worker",
    fatherIncome: "₱15,000/month",
    motherName: "Lorna Reyes Bautista",
    motherOccupation: "Vendor",
    motherIncome: "₱10,000/month",
    siblings: "4 (2 older sisters, 2 younger brothers)",
    familyIncome: "₱25,000/month",
    housingType: "Owned (Informal Settler)",
    scholarshipType: "Vocational and Technology Scholarship",
    scholarshipAmount: "₱15,000/semester",
    compliance: {
      gpa: { met: false, value: "2.1" },
      grades: { met: false, date: "Not Submitted" },
      events: { met: false, attended: 0, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: false },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: false },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: false },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: false }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "2.1", events: 0, status: "Non-Compliant" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "2.3", events: 1, status: "At Risk" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "2.6", events: 3, status: "Compliant" }
    ]
  },
  {
    id: "LM823745",
    firstName: "Michelle",
    middleName: "Torres",
    lastName: "Ramirez",
    initials: "MT",
    email: "michelle.ramirez@email.com",
    phone: "+63 920 567 8901",
    dateOfBirth: "February 14, 2002",
    gender: "Female",
    civilStatus: "Single",
    address: "45 Mabini St., Brgy. Poblacion, Makati City",
    barangay: "Poblacion",
    city: "Makati City",
    province: "Metro Manila",
    facebook: "facebook.com/michelle.ramirez",
    messenger: "m.me/michelle.ramirez",
    school: "Eulogio Amang Rodriguez Institute of Science and Technology",
    course: "BS Nursing",
    yearLevel: "4th Year",
    semester: "2nd Semester",
    programLevel: "Undergraduate",
    boardExam: "Nursing Board Exam",
    yearLevel: "4th Year",
    studentId: "2021-44556",
    scholarSince: "16 May 2024",
    status: "compliant",
    gpa: "3.0",
    requiredGpa: "2.5",
    gpaStatus: "Above Required",
    lastGradeSubmission: "Jan 22, 2026",
    eventsAttended: "3 of 3",
    fatherName: "Ricardo Torres Ramirez",
    fatherOccupation: "Security Guard",
    fatherIncome: "₱16,000/month",
    motherName: "Gloria Santos Ramirez",
    motherOccupation: "Factory Worker",
    motherIncome: "₱14,000/month",
    siblings: "1 (1 younger brother)",
    familyIncome: "₱30,000/month",
    housingType: "Rented",
    scholarshipType: "Tertiary Scholarship",
    scholarshipAmount: "₱28,000/semester",
    compliance: {
      gpa: { met: true, value: "3.0" },
      grades: { met: true, date: "Jan 22, 2026" },
      events: { met: true, attended: 3, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: true },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: true },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: true },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: true }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "3.0", events: 3, status: "Compliant" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "2.9", events: 4, status: "Compliant" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "2.8", events: 3, status: "Compliant" }
    ]
  },
  {
    id: "LM823744",
    firstName: "Daniel",
    middleName: "Aquino",
    lastName: "Valdez",
    initials: "DA",
    email: "daniel.valdez@email.com",
    phone: "+63 921 678 9012",
    dateOfBirth: "September 3, 2003",
    gender: "Male",
    civilStatus: "Single",
    address: "78 Rizal Ave., Brgy. Santo Niño, Marikina City",
    barangay: "Santo Niño",
    city: "Marikina City",
    province: "Metro Manila",
    facebook: "facebook.com/daniel.valdez",
    messenger: "m.me/daniel.valdez",
    school: "Technological University of the Philippines - Manila",
    course: "BS Information Technology",
    yearLevel: "3rd Year",
    semester: "1st Semester",
    programLevel: "Undergraduate",
    boardExam: null,
    studentId: "2022-77889",
    scholarSince: "28 May 2024",
    status: "at-risk",
    gpa: "2.7",
    requiredGpa: "2.5",
    gpaStatus: "Above Required",
    lastGradeSubmission: "Jan 18, 2026",
    eventsAttended: "1 of 3",
    fatherName: "Manuel Aquino Valdez",
    fatherOccupation: "Jeepney Driver",
    fatherIncome: "₱20,000/month",
    motherName: "Carmen Reyes Valdez",
    motherOccupation: "Sari-sari Store Owner",
    motherIncome: "₱12,000/month",
    siblings: "3 (1 older sister, 2 younger brothers)",
    familyIncome: "₱32,000/month",
    housingType: "Owned",
    scholarshipType: "Tertiary Scholarship",
    scholarshipAmount: "₱18,000/semester",
    compliance: {
      gpa: { met: true, value: "2.7" },
      grades: { met: true, date: "Jan 18, 2026" },
      events: { met: false, attended: 1, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: true },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: false },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: false },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: false }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "2.7", events: 1, status: "At Risk" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "2.8", events: 3, status: "Compliant" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "2.6", events: 4, status: "Compliant" }
    ]
  },
  {
    id: "LM823743",
    firstName: "Ana",
    middleName: "Mendoza",
    lastName: "Villanueva",
    initials: "AM",
    email: "ana.villanueva@email.com",
    phone: "+63 922 789 0123",
    dateOfBirth: "December 25, 2002",
    gender: "Female",
    civilStatus: "Single",
    address: "23 Bonifacio St., Brgy. Ugong, Valenzuela City",
    barangay: "Ugong",
    city: "Valenzuela City",
    province: "Metro Manila",
    facebook: "facebook.com/ana.villanueva",
    messenger: "m.me/ana.villanueva",
    school: "Pamantasan ng Lungsod ng Maynila",
    course: "BS Psychology",
    yearLevel: "3rd Year",
    semester: "2nd Semester",
    programLevel: "Undergraduate",
    boardExam: null,
    studentId: "2022-99001",
    scholarSince: "06 Jun 2024",
    status: "at-risk",
    gpa: "2.6",
    requiredGpa: "2.5",
    gpaStatus: "Above Required",
    lastGradeSubmission: "Jan 19, 2026",
    eventsAttended: "1 of 3",
    fatherName: "Jose Mendoza Villanueva",
    fatherOccupation: "Tricycle Driver",
    fatherIncome: "₱12,000/month",
    motherName: "Teresa Cruz Villanueva",
    motherOccupation: "Domestic Helper",
    motherIncome: "₱10,000/month",
    siblings: "5 (3 older brothers, 2 younger sisters)",
    familyIncome: "₱22,000/month",
    housingType: "Rented",
    scholarshipType: "KKFI Employee-Child Education Grant",
    scholarshipAmount: "₱15,000/semester",
    compliance: {
      gpa: { met: true, value: "2.6" },
      grades: { met: true, date: "Jan 19, 2026" },
      events: { met: false, attended: 1, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: true },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: false },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: false },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: false }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "2.6", events: 1, status: "At Risk" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "2.7", events: 2, status: "At Risk" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "2.8", events: 4, status: "Compliant" }
    ]
  },
  {
    id: "LM823742",
    firstName: "Bryan",
    middleName: "Dominguez",
    lastName: "Salazar",
    initials: "BD",
    email: "bryan.salazar@email.com",
    phone: "+63 923 890 1234",
    dateOfBirth: "April 10, 2003",
    gender: "Male",
    civilStatus: "Single",
    address: "56 Luna St., Brgy. Kamuning, Quezon City",
    barangay: "Kamuning",
    city: "Quezon City",
    province: "Metro Manila",
    facebook: "facebook.com/bryan.salazar",
    messenger: "m.me/bryan.salazar",
    school: "University of Makati",
    course: "BS Architecture",
    yearLevel: "2nd Year",
    semester: "1st Semester",
    programLevel: "Undergraduate",
    boardExam: null,
    studentId: "2023-22334",
    scholarSince: "10 Jun 2024",
    status: "non-compliant",
    gpa: "2.2",
    requiredGpa: "2.5",
    gpaStatus: "Below Required",
    lastGradeSubmission: "Dec 15, 2025",
    eventsAttended: "0 of 3",
    fatherName: "Roberto Dominguez Salazar",
    fatherOccupation: "Carpenter",
    fatherIncome: "₱18,000/month",
    motherName: "Linda Reyes Salazar",
    motherOccupation: "Seamstress",
    motherIncome: "₱8,000/month",
    siblings: "2 (1 older brother, 1 younger sister)",
    familyIncome: "₱26,000/month",
    housingType: "Owned",
    scholarshipType: "Vocational and Technology Scholarship",
    scholarshipAmount: "₱20,000/semester",
    compliance: {
      gpa: { met: false, value: "2.2" },
      grades: { met: true, date: "Dec 15, 2025" },
      events: { met: false, attended: 0, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: false },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: false },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: false },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: false }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "2.2", events: 0, status: "Non-Compliant" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "2.4", events: 2, status: "At Risk" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "2.7", events: 3, status: "Compliant" }
    ]
  },
  {
    id: "LM823741",
    firstName: "Kimberly Joy",
    middleName: "Castillo",
    lastName: "Pineda",
    initials: "KJ",
    email: "kimberly.pineda@email.com",
    phone: "+63 924 901 2345",
    dateOfBirth: "August 18, 2002",
    gender: "Female",
    civilStatus: "Single",
    address: "89 Aguinaldo St., Brgy. Grace Park, Caloocan City",
    barangay: "Grace Park",
    city: "Caloocan City",
    province: "Metro Manila",
    facebook: "facebook.com/kimberly.pineda",
    messenger: "m.me/kimberly.pineda",
    school: "Pamantasan ng Lungsod ng Pasay",
    course: "Bachelor of Elementary Education",
    yearLevel: "4th Year",
    semester: "2nd Semester",
    programLevel: "Undergraduate",
    boardExam: "LET",
    studentId: "2021-55667",
    scholarSince: "18 Jun 2024",
    status: "compliant",
    gpa: "3.3",
    requiredGpa: "2.5",
    gpaStatus: "Above Required",
    lastGradeSubmission: "Jan 21, 2026",
    eventsAttended: "3 of 3",
    fatherName: "Antonio Castillo Pineda",
    fatherOccupation: "Electrician",
    fatherIncome: "₱22,000/month",
    motherName: "Rosario Santos Pineda",
    motherOccupation: "Teacher (Public School)",
    motherIncome: "₱28,000/month",
    siblings: "1 (1 younger brother)",
    familyIncome: "₱50,000/month",
    housingType: "Owned",
    scholarshipType: "Tertiary Scholarship",
    scholarshipAmount: "₱12,000/semester",
    compliance: {
      gpa: { met: true, value: "3.3" },
      grades: { met: true, date: "Jan 21, 2026" },
      events: { met: true, attended: 3, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: true },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: true },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: true },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: false }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "3.3", events: 3, status: "Compliant" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "3.2", events: 4, status: "Compliant" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "3.1", events: 3, status: "Compliant" }
    ]
  },
  {
    id: "LM823740",
    firstName: "Janelle Faith",
    middleName: "Peralta",
    lastName: "Quinto",
    initials: "JF",
    email: "janelle.quinto@email.com",
    phone: "+63 925 012 3456",
    dateOfBirth: "May 30, 2003",
    gender: "Female",
    civilStatus: "Single",
    address: "12 Quezon Ave., Brgy. Pinyahan, Quezon City",
    barangay: "Pinyahan",
    city: "Quezon City",
    province: "Metro Manila",
    facebook: "facebook.com/janelle.quinto",
    messenger: "m.me/janelle.quinto",
    school: "Marikina Polytechnic College",
    course: "BS Environmental Science",
    yearLevel: "3rd Year",
    semester: "3rd Semester",
    programLevel: "Undergraduate",
    boardExam: null,
    studentId: "2022-88990",
    scholarSince: "20 Jul 2024",
    status: "compliant",
    gpa: "2.9",
    requiredGpa: "2.5",
    gpaStatus: "Above Required",
    lastGradeSubmission: "Jan 20, 2026",
    eventsAttended: "3 of 3",
    fatherName: "Eduardo Peralta Quinto",
    fatherOccupation: "Office Clerk",
    fatherIncome: "₱20,000/month",
    motherName: "Maricel Santos Quinto",
    motherOccupation: "Bank Teller",
    motherIncome: "₱25,000/month",
    siblings: "2 (2 younger sisters)",
    familyIncome: "₱45,000/month",
    housingType: "Rented",
    scholarshipType: "KKFI Employee-Child Education Grant",
    scholarshipAmount: "₱15,000/semester",
    compliance: {
      gpa: { met: true, value: "2.9" },
      grades: { met: true, date: "Jan 20, 2026" },
      events: { met: true, attended: 3, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: true },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: true },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: true },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: true }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "2.9", events: 3, status: "Compliant" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "2.8", events: 4, status: "Compliant" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "2.7", events: 3, status: "Compliant" }
    ]
  },
  {
    id: "LM823739",
    firstName: "Stephanie",
    middleName: "Gutierrez",
    lastName: "Manalo",
    initials: "SG",
    email: "stephanie.manalo@email.com",
    phone: "+63 926 123 4567",
    dateOfBirth: "October 12, 2002",
    gender: "Female",
    civilStatus: "Single",
    address: "34 Pasong Tamo St., Brgy. Sta. Cruz, Makati City",
    barangay: "Sta. Cruz",
    city: "Makati City",
    province: "Metro Manila",
    facebook: "facebook.com/stephanie.manalo",
    messenger: "m.me/stephanie.manalo",
    school: "Pamantasan ng Lungsod ng Valenzuela",
    course: "Master in Business Administration",
    yearLevel: "2nd Year",
    semester: "1st Semester",
    programLevel: "Masters",
    boardExam: "CPA",
    studentId: "2021-33445",
    scholarSince: "26 Jul 2024",
    status: "compliant",
    gpa: "3.1",
    requiredGpa: "2.5",
    gpaStatus: "Above Required",
    lastGradeSubmission: "Jan 19, 2026",
    eventsAttended: "3 of 3",
    fatherName: "Rolando Gutierrez Manalo",
    fatherOccupation: "Delivery Driver",
    fatherIncome: "₱18,000/month",
    motherName: "Evangeline Cruz Manalo",
    motherOccupation: "Cashier",
    motherIncome: "₱15,000/month",
    siblings: "3 (1 older sister, 2 younger brothers)",
    familyIncome: "₱33,000/month",
    housingType: "Rented",
    scholarshipType: "Tertiary Scholarship",
    scholarshipAmount: "₱22,000/semester",
    compliance: {
      gpa: { met: true, value: "3.1" },
      grades: { met: true, date: "Jan 19, 2026" },
      events: { met: true, attended: 3, required: 3 },
      violations: { met: true, count: 0 }
    },
    eventAttendance: [
      { name: "KKFI Scholars' Orientation and Community Day", date: "Mar 15, 2026", type: "Required", attended: true },
      { name: "Annual General Assembly 2026", date: "Apr 20, 2026", type: "Required", attended: true },
      { name: "Leadership Workshop for Scholars", date: "May 10, 2026", type: "Required", attended: true },
      { name: "Career Fair & Networking Night", date: "Jun 5, 2026", type: "Optional", attended: true }
    ],
    complianceHistory: [
      { period: "AY 2025-2026 (1st Sem)", gpa: "3.1", events: 3, status: "Compliant" },
      { period: "AY 2024-2025 (2nd Sem)", gpa: "3.0", events: 4, status: "Compliant" },
      { period: "AY 2024-2025 (1st Sem)", gpa: "2.9", events: 3, status: "Compliant" }
    ]
  }
];

const applicants = [
  {
    id: "AP2026001",
    firstName: "Angela",
    middleName: "Reyes",
    lastName: "Santos",
    initials: "AR",
    email: "angela.santos@email.com",
    phone: "+63 927 234 5678",
    dateOfBirth: "January 5, 2005",
    gender: "Female",
    civilStatus: "Single",
    address: "15 Magsaysay Blvd., Brgy. San Antonio, Pasig City",
    barangay: "San Antonio",
    city: "Pasig City",
    province: "Metro Manila",
    facebook: "facebook.com/angela.santos",
    messenger: "m.me/angela.santos",
    school: "Rizal Technological University",
    course: "BS Computer Engineering",
    yearLevel: "Incoming 1st Year",
    applicationDate: "Jan 15, 2026",
    status: "pending",
    fatherName: "Antonio Reyes Santos",
    fatherOccupation: "Welder",
    fatherIncome: "₱16,000/month",
    motherName: "Cynthia Cruz Santos",
    motherOccupation: "Housewife",
    motherIncome: "N/A",
    siblings: "2 (1 older brother, 1 younger sister)",
    familyIncome: "₱16,000/month",
    housingType: "Rented",
    lastGpa: "1.5",
    documents: {
      applicationForm: true,
      gradesCopy: true,
      birthCertificate: true,
      indigancyCertificate: true,
      photo: true,
      enrollmentCert: false
    }
  },
  {
    id: "AP2026002",
    firstName: "Kenneth",
    middleName: "Lim",
    lastName: "Garcia",
    initials: "KL",
    email: "kenneth.garcia@email.com",
    phone: "+63 928 345 6789",
    dateOfBirth: "March 22, 2005",
    gender: "Male",
    civilStatus: "Single",
    address: "78 Gen. Luna St., Brgy. Rosario, Pasig City",
    barangay: "Rosario",
    city: "Pasig City",
    province: "Metro Manila",
    facebook: "facebook.com/kenneth.garcia",
    messenger: "m.me/kenneth.garcia",
    school: "Pamantasan ng Lungsod ng Muntinlupa",
    course: "BS Accountancy",
    yearLevel: "Incoming 1st Year",
    applicationDate: "Jan 18, 2026",
    status: "under-review",
    fatherName: "Roberto Lim Garcia",
    fatherOccupation: "Factory Worker",
    fatherIncome: "₱14,000/month",
    motherName: "Maria Santos Garcia",
    motherOccupation: "Laundrywoman",
    motherIncome: "₱6,000/month",
    siblings: "4 (2 older sisters, 2 younger brothers)",
    familyIncome: "₱20,000/month",
    housingType: "Owned (Informal)",
    lastGpa: "1.3",
    documents: {
      applicationForm: true,
      gradesCopy: true,
      birthCertificate: true,
      indigancyCertificate: true,
      photo: true,
      enrollmentCert: true
    }
  },
  {
    id: "AP2026003",
    firstName: "Patricia",
    middleName: "Dela Cruz",
    lastName: "Mercado",
    initials: "PD",
    email: "patricia.mercado@email.com",
    phone: "+63 929 456 7890",
    dateOfBirth: "June 14, 2004",
    gender: "Female",
    civilStatus: "Single",
    address: "23 Sampaguita St., Brgy. Manggahan, Pasig City",
    barangay: "Manggahan",
    city: "Pasig City",
    province: "Metro Manila",
    facebook: "facebook.com/patricia.mercado",
    messenger: "m.me/patricia.mercado",
    school: "Pamantasan ng Lungsod ng San Pablo",
    course: "BS Nursing",
    yearLevel: "2nd Year (Transferee)",
    applicationDate: "Jan 10, 2026",
    status: "approved",
    fatherName: "Fernando Dela Cruz Mercado",
    fatherOccupation: "Deceased",
    fatherIncome: "N/A",
    motherName: "Elena Santos Mercado",
    motherOccupation: "Street Vendor",
    motherIncome: "₱10,000/month",
    siblings: "3 (1 older brother, 2 younger sisters)",
    familyIncome: "₱10,000/month",
    housingType: "Rented",
    lastGpa: "1.6",
    documents: {
      applicationForm: true,
      gradesCopy: true,
      birthCertificate: true,
      indigancyCertificate: true,
      photo: true,
      enrollmentCert: true
    }
  },
  {
    id: "AP2026004",
    firstName: "Jerome",
    middleName: "Villanueva",
    lastName: "Tan",
    initials: "JV",
    email: "jerome.tan@email.com",
    phone: "+63 930 567 8901",
    dateOfBirth: "September 8, 2005",
    gender: "Male",
    civilStatus: "Single",
    address: "56 Quezon St., Brgy. Maybunga, Pasig City",
    barangay: "Maybunga",
    city: "Pasig City",
    province: "Metro Manila",
    facebook: "facebook.com/jerome.tan",
    messenger: "m.me/jerome.tan",
    school: "Taguig City University",
    course: "BS Electrical Engineering",
    yearLevel: "Incoming 1st Year",
    applicationDate: "Jan 20, 2026",
    status: "pending",
    fatherName: "William Villanueva Tan",
    fatherOccupation: "Tricycle Driver",
    fatherIncome: "₱12,000/month",
    motherName: "Rowena Cruz Tan",
    motherOccupation: "Store Clerk",
    motherIncome: "₱11,000/month",
    siblings: "1 (1 younger sister)",
    familyIncome: "₱23,000/month",
    housingType: "Owned",
    lastGpa: "1.4",
    documents: {
      applicationForm: true,
      gradesCopy: true,
      birthCertificate: true,
      indigancyCertificate: false,
      photo: true,
      enrollmentCert: false
    }
  },
  {
    id: "AP2026005",
    firstName: "Kristine Mae",
    middleName: "Bautista",
    lastName: "Reyes",
    initials: "KB",
    email: "kristine.reyes@email.com",
    phone: "+63 931 678 9012",
    dateOfBirth: "November 30, 2004",
    gender: "Female",
    civilStatus: "Single",
    address: "90 Rizal St., Brgy. Pinagbuhatan, Pasig City",
    barangay: "Pinagbuhatan",
    city: "Pasig City",
    province: "Metro Manila",
    facebook: "facebook.com/kristine.reyes",
    messenger: "m.me/kristine.reyes",
    school: "University of Caloocan City",
    course: "BS Psychology",
    yearLevel: "Incoming 1st Year",
    applicationDate: "Jan 22, 2026",
    status: "rejected",
    rejectionReason: "Family income exceeds threshold",
    fatherName: "Ernesto Bautista Reyes",
    fatherOccupation: "Manager",
    fatherIncome: "₱65,000/month",
    motherName: "Victoria Santos Reyes",
    motherOccupation: "Nurse",
    motherIncome: "₱45,000/month",
    siblings: "1 (1 younger brother)",
    familyIncome: "₱110,000/month",
    housingType: "Owned",
    lastGpa: "1.2",
    documents: {
      applicationForm: true,
      gradesCopy: true,
      birthCertificate: true,
      indigancyCertificate: false,
      photo: true,
      enrollmentCert: true
    }
  }
];

// Utility functions to get data
function getScholarById(id) {
  return scholars.find(s => s.id === id);
}

function getApplicantById(id) {
  return applicants.find(a => a.id === id);
}

function getScholarsByStatus(status) {
  return scholars.filter(s => s.status === status);
}

function getApplicantsByStatus(status) {
  return applicants.filter(a => a.status === status);
}

// Get scholar from URL parameter
function getScholarFromUrl() {
  const params = new URLSearchParams(window.location.search);
  const id = params.get('id');
  return id ? getScholarById(id) : null;
}

// Get applicant from URL parameter
function getApplicantFromUrl() {
  const params = new URLSearchParams(window.location.search);
  const id = params.get('id');
  return id ? getApplicantById(id) : null;
}
